[package]
name = "acrostiche"
version = "0.3.6"
entrypoint = "acrostiche.typ"
repository = "https://github.com/Grisely/packages"
authors = ["Grizzly"]
license = "MIT"
keywords = ["acronyms"]
categories = ["utility","model"]
description = "Manage acronyms and their definitions in Typst."
